export const dynamicPageUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/pages?status=publish`
export const newsUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/posts`
export const navigationUrl = `${process.env.NEXT_PUBLIC_HOST_V1}/pages`
export const socialMediaUrl = `${process.env.NEXT_PUBLIC_HOST}/social`
export const analyzesUrl = `${process.env.NEXT_PUBLIC_HOST_V2}/products`
export const registerUrl = `${process.env.NEXT_PUBLIC_HOST_V2}/customers?${process.env.NEXT_PUBLIC_CONSUMER_KEY}&${process.env.NEXT_PUBLIC_CONSUMER_SECRET}`
export const loginUrl = `${process.env.NEXT_PUBLIC_HOST_LOGIN}/token`
export const changePasswordUrl = ``
export const editProfileUrl = `${process.env.NEXT_PUBLIC_HOST_V2}/customers`
export const orderUrl = `${process.env.NEXT_PUBLIC_HOST_V2}/orders`
export const analyzesCategoryUrl = `${process.env.NEXT_PUBLIC_HOST_V2}/products/categories`
export const slidesUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/home_slider`
export const allPagesUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/pages?status=publish`
export const aboutUsTextUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/aboutUs`
export const locationsUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/locations`
export const contactInfoUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/pages/?status=publish&slug=contact-us`
export const resultsUrl = `${process.env.NEXT_PUBLIC_HOST_RESULTS}`
export const resultsPdfUrl = `${process.env.NEXT_PUBLIC_HOST_RESULTS_PDF}`
export const callHomeUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/pages/?status=publish&slug=call-home`
export const aboutUsUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/pages/?status=publish&slug=about-us`
export const doctorsUsUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/doctors?_embed&status=publish`
export const equipmentUrl = `${process.env.NEXT_PUBLIC_HOST_WP}/equipment?_embed&status=publish`
export const qualityControlUrl = `${process.env.NEXT_PUBLIC_HOST}/quality-control`
export const footerLeftLinksUrl = `${process.env.NEXT_PUBLIC_HOST_MENU}/footer-left`
export const footerRightLinksUrl = `${process.env.NEXT_PUBLIC_HOST_MENU}/footer-right`

