export const dynamicPageUrl = 'http://localhost:4500/page'
export const newsUrl = 'http://localhost:4500/news/'
export const navigationUrl = 'http://localhost:4500/pages'
export const socialMediaUrl = 'http://localhost:4500/social'
export const analyzesUrl = 'http://localhost:4500/analyzes/'
export const registerUrl = 'http://localhost:8000/auth/register'
export const loginUrl = 'http://localhost:8000/auth/login'
export const changePasswordUrl = 'http://localhost:8000/auth/change-password'
export const editProfileUrl = 'http://localhost:8000/auth/edit-profile'
export const orderUrl = 'http://localhost:4500/orders'
export const homeCallOrdersUrl = 'http://localhost:4500/homeCallOrders'
export const analyzesTypesUrl = 'http://localhost:4500/analyzes-types'
export const analyzesCategoryUrl = 'http://localhost:4500/categories'
export const slidesUrl = 'http://localhost:4500/slides'
export const researchesUrl = 'http://localhost:4500/researches'
export const aboutUsTextUrl = 'http://localhost:4500/aboutUs'
export const locationsUrl = 'http://localhost:4500/locations'
export const contactFormMessageUrl = 'http://localhost:4500/messages'
export const contactInfoUrl = 'http://localhost:4500/contactInfo'
export const resultsUrl = 'http://localhost:4500/results'
export const callHomeUrl = 'http://localhost:4500/call-home-text'
export const aboutUsUrl = 'http://localhost:4500/about-us'
export const doctorsUsUrl = 'http://localhost:4500/doctors'
export const equipmentUrl = 'http://localhost:4500/equipment'
export const qualityControlUrl = 'http://localhost:4500/quality-control'



